### PR TITLE
fix: return type of LTITool->getDataConnector()

### PR DESCRIPTION
**Pull request by pavlserg**

### CODE REVIEW

**Comment by chrispittman** [comment]
Hi.  Thank you for the pull request!

Can you explain why `ceLTIc\LTI\DataConnector` is the correct return type here?

**Comment by pavlserg** [comment]
Hi.
Thank you for attention.
Current return type is `LonghornOpen\LaravelCelticLTI\ceLTIc\LTI\DataConnector\DataConnector`
Снимок экрана 2023-12-19 в 11 09 29 . I think it is just little sintaxis mistake. 
`ceLTIc\LTI\DataConnector` is the correct return type because this library is a wrapper for celtic library.

**Comment by pavlserg** [comment]
fix `ceLTIc\LTI\DataConnector` to `ceLTIc\LTI\DataConnector\DataConnector`

**Comment by chrispittman** [comment]
Got it.  Thank you!

**Pull request merged**
